# Generated by Django 6.0.2 on 2026-03-19 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Voter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('st_num', models.TextField()),
                ('st_name', models.TextField()),
                ('ap_num', models.IntegerField()),
                ('zip_code', models.IntegerField()),
                ('dob', models.DateTimeField()),
                ('dor', models.DateTimeField()),
                ('party_affil', models.CharField(max_length=2)),
                ('precinct_num', models.IntegerField()),
                ('v20state', models.TextField()),
                ('v21town', models.TextField()),
                ('v21primary', models.TextField()),
                ('v22general', models.TextField()),
                ('v23town', models.TextField()),
            ],
        ),
    ]
