# Generated by Django 6.0.2 on 2026-04-05 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voter_analytics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='voter',
            name='ap_num',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dob',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='dor',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='voter',
            name='precinct_num',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='voter',
            name='zip_code',
            field=models.IntegerField(blank=True),
        ),
    ]
