# Generated by Django 6.0.2 on 2026-02-13 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mini_insta', '0002_article_image_url'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.TextField()),
                ('display_name', models.TextField()),
                ('bio_text', models.TextField()),
                ('join_date', models.DateTimeField(auto_now=True)),
                ('profile_image_url', models.URLField(blank=True)),
            ],
        ),
    ]
