# Generated by Django 6.0.2 on 2026-04-30 17:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TradingCG', '0002_user_auth_user_user_latitude_user_longitude_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traderequest',
            name='offered_card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trade_offers', to='TradingCG.collectioncard'),
        ),
        migrations.AlterField(
            model_name='traderequest',
            name='status',
            field=models.TextField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='pending'),
        ),
    ]
